// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zczbjpvwonklkvukpviy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjemJqcHZ3b25rbGt2dWtwdml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTE5MDcsImV4cCI6MjA2OTI4NzkwN30.xUjqVo8JiR9Qc_WfqXsXQ0wpKjlHx8vtwDwbZrrGptc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});